// Generated by CoffeeScript 1.3.3
(function() {
  var TestClass,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  exports.TestClass = TestClass = (function() {

    function TestClass() {
      this.myValue = __bind(this.myValue, this);

    }

    TestClass.prototype.myValue = function() {
      return 100;
    };

    return TestClass;

  })();

}).call(this);
